### ISSUE TITLE
Update List Button

### ISSUE THREAD

**Issue by seringsergio** [Zolertia/Resources#2]
I tested the tutorial **https://github.com/Zolertia/Resources/wiki/Sparrow** and i worked perfectly. Thank you very much for the tutorial. However, when i hit the **Update List Button** (in the Sparrow demo) i got the following message:

list routes 1485535302.81
refreshing routes...
fetching routes from: fd02::212:4b00:615:aa72
adding device: fd02::212:4b00:616:f3d
add_device() takes at least 3 arguments (2 given)
DemoSocket: Unexpected error handling cmd: routes <type 'exceptions.TypeError'>

The problem is that i do not see the device in the **6loWPAN Devices** tab. I am able to ping6 the Border Router's interface, the slip radio and the device (a different RE-Mote). I try the Sparrow demo on Chrome and Firefox with the same results.

**Comment by amejias** [comment]
Solved in repository.
