### ISSUE TITLE
Need to add further toolchain in the Wiki for serial login

### ISSUE THREAD

**Issue by shantanoo-desai** [Zolertia/Resources#3]
Hi,

Apparently, one also requires to install `lib32z1` & `lib32ncurses5` to the Toolchain installation if one wishes to use `make login PORT=/dev/ttyUSB0`.

### Observations

1. I have Zoul Rev-A modules with me and I cloned Contiki to my Ubuntu VM.
2. I installed the `gcc-arm-none-eabi` and `gdb-arm-none-eabi`
3. went into the `/examples/zolertial/zoul/` and `make TARGET=zoul BOARD=zoul-reva zoul-demo.upload && serialdump0`
4. `serialdump0` is not a command line but I went ahead and did `make login PORT=/dev/ttyUSB0` but the error 
        sky/tools/serialdump-linux: Command not found
occured.
5. upon `sudo apt-get install lib32ncurses5 lib32z1` and `make login` gives me the data.

Not sure if this was a hack on myside but I thought this might be good information. 
[Source=> check number 6](https://adilaways.wordpress.com/category/contiki/)

**Comment by amejias** [comment]
Serialdump0 is an alias of serialdump-linux located in /tools/sky (just renamed serialdump-linux)

   Once compiled, add this alias line in .bashrc:
   alias serialdump0="serialdump -b115200 /dev/ttyUSB0"
